### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by Zahra-Zamanshoar** [pooya-mohammadi/intro_to_git#1]
Hi 
dear pooya :D
What is touch  inside  description Create a .gitignore file?
![image](https://user-images.githubusercontent.com/103884658/200114461-3be66396-4b5b-4075-90d7-c470dfd0c94a.png)
@pooya-mohammadi

**Comment by pooya-mohammadi** [comment]
Hi dear @Zzamani80 
It's a Linux command. In this example, I used it to create an empty text file, namely, `.gitignore`. If you are working on Windows, simply create a new text file graphically and rename it to `.gitignore`.
I added a brief description to the main file as well.
If you have any further questions, feel free to comment below.
